pub mod airtable;
pub mod calendar;
pub mod chrome;
pub mod files;
pub mod github;
pub mod gitlab;
pub mod gmail;
pub mod imessage;
pub mod jira;
pub mod linear;
pub mod notion;
pub mod notes;
pub mod obsidian;
pub mod safari;
pub mod slack;
pub mod splitter;
pub mod terminal;
pub mod todoist;
pub mod trello;
pub mod watcher;
mod checksum;

pub use airtable::AirtableHarvester;
pub use calendar::CalendarHarvester;
pub use chrome::ChromeHarvester;
pub use files::FileHarvester;
pub use github::GithubHarvester;
pub use gitlab::GitlabHarvester;
pub use gmail::{GmailConfig, GmailHarvester};
pub use imessage::IMessageHarvester;
pub use jira::JiraHarvester;
pub use linear::LinearHarvester;
pub use notion::NotionHarvester;
pub use notes::NotesHarvester;
pub use obsidian::ObsidianHarvester;
pub use safari::SafariHarvester;
pub use slack::SlackHarvester;
pub use terminal::TerminalHarvester;
pub use todoist::TodoistHarvester;
pub use trello::TrelloHarvester;
pub use watcher::{start as start_watcher, WatchEvent};
